default_charset = "UTF-8"
mbstring.internal_encoding = UTF-8

; エラー設定
display_errors = Off
log_errors = On
error_reporting = E_ALL

; PHPバージョン非表示
expose_php = Off

; ファイルアップロード設定
upload_max_filesize = 32M
post_max_size = 32M